apiVersion: v1
kind: Pod
metadata:
  # pods need unique names otherwise manifests overwrite each other
  name: webapp-release-0-5
  labels:
    app: webapp
    release: 0-5
spec:
  containers:
    - name: webapp
      image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5