apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongodb

spec:
  # This defines which pods are going to be represented by this service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (browser)
  selector:
    app: mongodb
    # change selectors to the right labels to direct traffic accordingly

  ports:
    - name: mongoport
      port: 27017

  # Nodeport allows traffic forwarding from container to host
  type: ClusterIP


