apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue

spec:
  # This defines which pods are going to be represented by this service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (browser)
  selector:
    app: queue
    # change selectors to the right labels to direct traffic accordingly

  ports:
    - name: http
      port: 8161
      nodePort: 30010

  # If only internal and not external
  # type: ClusterIP
  # Nodeport allows traffic forwarding from container to host
  type: NodePort


