apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp

spec:
  # This defines which pods are going to be represented by this service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (browser)
  selector:
    app: webapp
    release: 0-0
    # change selectors to the right labels to direct traffic accordingly

  ports:
    - name: http
      port: 80
      nodePort: 30080

  # If only internal and not external
  # type: ClusterIP
  # Nodeport allows traffic forwarding from container to host
  type: NodePort


